"""empty message

Revision ID: cc1c9f012263
Revises: 
Create Date: 2020-09-17 16:02:11.788485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1c9f012263'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=10), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=10), nullable=False),
    sa.Column('password', sa.String(length=15), nullable=False),
    sa.Column('phone', sa.String(length=11), nullable=False),
    sa.Column('is_delete', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('interface',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inf_url', sa.String(length=50), nullable=False),
    sa.Column('inf_name', sa.String(length=10), nullable=False),
    sa.Column('req_method', sa.String(length=10), nullable=False),
    sa.Column('req_parameters', sa.String(length=150), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('create_person', sa.String(length=10), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interface')
    op.drop_table('user')
    op.drop_table('project')
    # ### end Alembic commands ###
